name: Winfinitricks2
main: us.windevsystems.winfinitrix2.Winfinitrix2
version: 2.0.0
author: IsMyAmpTooHigh
description: Custom commands for Win (and co.) to use.
commands:
  fling:
    description: WHEEEEEEEEEEEEEEEEEEEEEEE!
    usage: /fling [player]
  ctb:
    description: Catch the bus (kill yourself).
    usage: /ctb